FROM node:20-alpine
WORKDIR /app

# Set environment to production
ENV NODE_ENV=production

COPY package*.json ./
# Install only production dependencies
RUN npm install --production

COPY . .

# Render dynamically sets the PORT env variable
EXPOSE 5001

CMD ["npm", "start"]
